services:
  postgres:
    image: postgres:15-alpine
    container_name: gamevault_db
    environment:
      POSTGRES_DB: gamevault_test
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: devpass123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d gamevault_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: